//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOgrenciOtomasyonuEntities : DbContext
    {
        public DbOgrenciOtomasyonuEntities()
            : base("name=DbOgrenciOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumlers> Bolumlers { get; set; }
        public virtual DbSet<Ogrencilers> Ogrencilers { get; set; }
        public virtual DbSet<Siniflars> Siniflars { get; set; }
        public virtual DbSet<Kullanicilars> Kullanicilars { get; set; }
    }
}
