//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrencilers
    {
        public int ogrid { get; set; }
        public string ograd { get; set; }
        public string ogrsoyad { get; set; }
        public Nullable<int> Siniflar_sinifid { get; set; }
    
        public virtual Siniflars Siniflars { get; set; }
    }
}
