//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siniflars()
        {
            this.Ogrencilers = new HashSet<Ogrencilers>();
        }
    
        public int sinifid { get; set; }
        public string sinifad { get; set; }
        public Nullable<int> Bolumler_bolumid { get; set; }
    
        public virtual Bolumlers Bolumlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrencilers> Ogrencilers { get; set; }
    }
}
